env:
  global:
    - K8S_RELEASE: 1.21.0
    - BUILD_PATH: /home/travis/gopath
language: go
go:
  - 1.16.3

install:
- mkdir -p ${BUILD_PATH}/src/k8s.io
- wget https://github.com/kubernetes/kubernetes/archive/v${K8S_RELEASE}.tar.gz -O ${BUILD_PATH}/src/k8s.io/kubernetes-src.tar.gz
- pushd ${BUILD_PATH}/src/k8s.io && tar xzf kubernetes-src.tar.gz && mv kubernetes-${K8S_RELEASE} kubernetes && popd
- pushd ${BUILD_PATH}/src/k8s.io/kubernetes && make generated_files && popd

script:
- make comp
- make genresources
- make api
- make configapi
# - make cli
